// <auto-generated />
namespace MPTKDDataEntry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_holiday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_holiday));
        
        string IMigrationMetadata.Id
        {
            get { return "201609301415137_add_holiday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
